language: node_js

cache:
  directories:
    - "node_modules"

script:
  - yarn
  - yarn build
  - mv build gh_pages

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
   on:
     # temporary comment for the bugfix
     # branch: master
     branch: bugfix/gh_pages_rendering
   target_branch: gh-pages # default value
