language: node_js

cache:
  directories:
    - "node_modules"

script:
  - yarn install --offline --pure-lockfile
  - yarn build
  - rm README.md
  - mv build/* .

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
   on:
     branch: master
   target_branch: gh-pages # default value
